eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
security:
  oauth2:
    client:
      client-id: vntg_auth
      client-secret: vntg_secret
    resource:
      jwt:
        key-value: jwt_secret_key
server:
  port: 8000
spring:
  application:
    name: msa-user-api
  cloud:
    stream:
      bindings:
        join:
          destination: join_after
          group: join
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/spring_msa?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&tinyInt1isBit=false
      password: msauser
      username: msauser
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true